name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Bandit Security Scan
      run: |
        pip install bandit
        bandit -r app

    - name: Run Safety Vulnerability Check
      run: |
        pip install safety
        safety check --full-report
    
    - name: Run Bandit Security Scan
      uses: tj-actions/bandit@v4
      with:
        path: app
        options: "-r -lll"

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-gh-actions-app:latest .

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-gh-actions-app:latest
